function [fitresult, gof] = fitting(t, unshaped)
%CREATEFIT(T,UNSHAPED)
%  Create a fit.
%
%  Data for 'fitsave copy 2' fit:
%      X Input : t
%      Y Output: unshaped
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Dec-2018 17:11:03


%% Fit: 'fitsave copy 2'.
[xData, yData] = prepareCurveData( t, unshaped );

% Set up fittype and options.
ft = fittype( 'a*exp((sigma^2-2*(t-t0)*tau)/(2*tau^2))*(1+erf((-sigma^2+(t-t0)*tau)/(sqrt(2)*tau*sigma)))+y0', 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.DiffMinChange = 1E-8;
opts.Display = 'Off';
opts.Lower = [0.001 1 100 100 -0.005];
opts.MaxFunEvals = 1000;
opts.MaxIter = 1000;
opts.Robust = 'On';
opts.StartPoint = [0.005 10 1000 2500 0];
opts.Upper = [0.1 100 10000 10000 0.005];

% Fit model to data.
[fitresult,gof] = fit( xData, yData, ft, opts );

%{
% Plot fit with data.
figure( 'Name', 'fitsave copy 2' );
h = plot( fitresult, xData, yData );
legend( h, 'HPGe pulse', 'fit', 'Location', 'NorthEast' );
% Label axes
xlabel t
ylabel unshaped
grid off
%}

